name: macOS

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macOS-latest
        raku-version:
          - '2025.06.1'
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Test
        run: prove -e 'raku -I.' --ext .rakutest t
      - name: Add Pakku
        run: raku -I. bin/pakku nobar nospinner verbose all add .
      - name: Add a dist from fez
        run: pakku nobar nospinner verbose all add rak
      - name: Search, info, state
        run: |
          pakku nobar nospinner search Cro::HTTP
          pakku nobar nospinner info rak
          pakku nobar nospinner state
