name: macOS

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  raku:
    strategy:
      matrix:
        os:
          - macOS-latest
        raku-version:
          - 'latest'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Raku/setup-raku@v1
        with:
          raku-version: ${{ matrix.raku-version }}
      - name: Add Pakku
        run: raku -I. bin/pakku nobar nospinner verbose all add .
      - name: Add Distribution
        run: pakku nobar nospinner verbose all add rak
